---
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: managed-cluster-placements
spec:
  remediationAction: enforce
  severity: high
  object-templates-raw: |-
    {{/* ##  Gather all the managed clusters  ## */}}
    {{- range $mc := (lookup "cluster.open-cluster-management.io/v1" "ManagedCluster" "" "").items }}
      {{- $mcname := $mc.metadata.name }}
    - complianceType: musthave
      objectDefinition:
        apiVersion: cluster.open-cluster-management.io/v1beta1
        kind: Placement
        metadata:
          name: {{ $mcname }}
          namespace: policies
        spec:
          predicates:
            - requiredClusterSelector:
                labelSelector:
                  matchExpressions:
                    - key: name
                      operator: In
                      values:
                        - {{ $mcname }}
    {{- end }}
