---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policies-nonprod
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: cluster-management
  source:
    path: policies-nonprod/environments/nonprod #Could use overlays for per cluster paths if needed for active/passive ACM
    repoURL: ""
    targetRevision: main
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      selfHeal: true
