---
apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: self-node-remediation-operator
spec:
  complianceType: musthave
  complianceConfig:
    catalogSourceUnhealthy: NonCompliant
    deploymentsUnavailable: NonCompliant
    upgradesAvailable: Compliant
  remediationAction: enforce
  removalBehavior:
    clusterServiceVersions: Delete
    customResourceDefinitions: Delete
    operatorGroups: DeleteIfUnused
    subscriptions: Delete
  severity: critical
  upgradeApproval: None
  subscription:
    channel: stable
    name: self-node-remediation
    namespace: openshift-workload-availability
    source: redhat-operators
    sourceNamespace: openshift-marketplace
  operatorGroup:
    name: workload-availability-operator-group
    namespace: openshift-workload-availability
