---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: gen-policy-placement
policyDefaults:
  namespace: policies
  remediationAction: enforce
  pruneObjectBehavior: DeleteIfCreated
  ## turn off the default compliance annotations
  categories: []
  controls: []
  standards: []
  policySets:
    - acm-placement-toleration
placementBindingDefaults:
  name: acm-placement-toleration-binding
policies:
  - name: acm-placement-tolerations
    remediationAction: enforce
    manifests:
      - path: ensure-placement-toleration.yaml
policySets:
  - name: acm-placement-toleration
    placement:
      placementName: hub-clusters
