---
apiVersion: v1
kind: Secret
metadata:
  name: CHANGEME
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: ''
  password: ADOTOKEN
  username: ADOUSER
