---
apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: lso-operator-install
spec:
  complianceType: musthave
  complianceConfig:
    catalogSourceUnhealthy: NonCompliant
    deploymentsUnavailable: NonCompliant
    upgradesAvailable: Compliant
  remediationAction: enforce
  removalBehavior:
    clusterServiceVersions: Delete
    customResourceDefinitions: Delete
    operatorGroups: DeleteIfUnused
    subscriptions: Delete
  severity: high
  upgradeApproval: None
  subscription:
    channel: stable
    name: local-storage-operator
    namespace: openshift-local-storage
    source: redhat-operators
    sourceNamespace: openshift-marketplace
  operatorGroup:
    name: odf-operator
    targetNamespaces:
      - openshift-local-storage
