---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: gen-policy-generator-policy-alerts
policyDefaults:
  namespace: policies
  remediationAction: enforce
  ## set the default compliance annotations
  categories: []
  controls: []
  standards: []
  policySets:
    - acm-alerts-placements
placementBindingDefaults:
  name: acm-alerts-placement-binding
policies:
  - name: acm-policy-alerts
    remediationAction: enforce
    configurationPolicyAnnotations:
      policy.open-cluster-management.io/disable-templates: 'true'
    manifests:
      - path: namespace.yaml
      - path: policy-prometheusrule.yaml
policySets:
  - name: acm-alerts-placements
    placement:
      placementName: hub-clusters
