---
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: custom-operators-icsp-dynamic
spec:
  remediationAction: enforce
  object-templates-raw: |
    {{hub- range $cmap := (lookup "v1" "ConfigMap" "" "").items hub}}
      {{hub- if contains "disconnected-custom-operator-" $cmap.metadata.name hub}}
        {{hub- $step := split "disconnected-custom-operator-" $cmap.metadata.name hub}}
        {{hub- $name := $step._1 hub}}
    - complianceType: mustonlyhave
      objectDefinition:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: custom-operator-index-{{hub $name hub}}-generated
          namespace: disconnected-config
        data:
          icsp.yaml: |
            apiVersion: operator.openshift.io/v1alpha1
            kind: ImageContentSourcePolicy
            metadata:
              name: operator-{{hub $name  hub}}
            spec:
              repositoryDigestMirrors:
              {{hub- $object := fromConfigMap "policies" $cmap.metadata.name "imageContentSourcePolicy.yaml"  hub}}
              {{hub- range $item := split "\n" $object  hub}}
                {{hub- if contains "source: " $item  hub}}
                  {{hub- $midStep := split "/" $item hub}}
                  {{hub- $operator := $midStep._1 hub}}
              - mirrors:
                - registry-quay-quay.apps.{{ fromConfigMap "openshift-config" "cluster-info" "hub_primary" }}.ocp1.example.com/oc-mirror/{{hub $operator  hub}}
                - registry-quay-quay.apps.{{ fromConfigMap "openshift-config" "cluster-info" "hub_backup" }}.ocp1.example.com/oc-mirror/{{hub $operator  hub}}
                {{hub $item | autoindent hub}}
                {{hub- end hub}}
              {{hub- end hub}}
          change_tracker: resversion-{{hub $cmap.metadata.resourceVersion hub}}
    - complianceType: mustonlyhave
      objectDefinition:
        apiVersion: operators.coreos.com/v1alpha1
        kind: CatalogSource
        metadata:
          name: custom-operator-index-{{hub $name hub}}
          namespace: openshift-marketplace
        spec:
          {{hub- $object := fromConfigMap "policies" $cmap.metadata.name "singleCatalogSource.yaml"  hub}}
          {{hub- range $item := split "\n" $object  hub}}
            {{hub- if contains "image: " $item  hub}}
          {{hub $item | autoindent hub}}
          sourceType: grpc
            {{hub- end hub}}
          {{hub- end hub}}
      {{hub- end hub}}
    {{hub- end hub}}
